name: thumbnail_gen
description: A thumbnail generator API
version: 0.0.1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  image: ^3.2.0
  path: ^1.8.0
  shelf: ^1.3.2
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
